/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        primary: {
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          900: '#164e63',
          DEFAULT: '#06b6d4',
        },
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        ring: 'hsl(var(--ring))',
        gray: {
          750: '#2d3748',
          850: '#1a202c',
          950: '#0d1117',
        },
        brand: {
          yellow: 'hsl(var(--brand-yellow))',
          magenta: 'hsl(var(--brand-magenta))',
          cyan: 'hsl(var(--brand-cyan))',
          violet: 'hsl(var(--brand-violet))',
          blue: 'hsl(var(--brand-blue))',
          black: 'hsl(var(--brand-black))',
        },
        slate: {
          50: 'hsl(var(--slate-50))',
          100: 'hsl(var(--slate-100))',
          200: 'hsl(var(--slate-200))',
          300: 'hsl(var(--slate-300))',
          400: 'hsl(var(--slate-400))',
          500: 'hsl(var(--slate-500))',
          600: 'hsl(var(--slate-600))',
          700: 'hsl(var(--slate-700))',
          800: 'hsl(var(--slate-800))',
          900: 'hsl(var(--slate-900))',
          950: 'hsl(var(--slate-950))',
        },
        sky: {
          50: 'hsl(var(--sky-50))',
          100: 'hsl(var(--sky-100))',
          200: 'hsl(var(--sky-200))',
          300: 'hsl(var(--sky-300))',
          400: 'hsl(var(--sky-400))',
          500: 'hsl(var(--sky-500))',
          600: 'hsl(var(--sky-600))',
          700: 'hsl(var(--sky-700))',
          800: 'hsl(var(--sky-800))',
          900: 'hsl(var(--sky-900))',
        },
      },
      borderRadius: {
        lg: '0.5rem',
        md: '0.375rem',
        sm: '0.25rem',
      },
      boxShadow: {
        'surface-light': '0 14px 30px -18px rgba(15, 23, 42, 0.28), 0 3px 12px -8px rgba(15, 23, 42, 0.12)',
        'surface-dark': '0 18px 36px -18px rgba(2, 6, 23, 0.7), 0 6px 18px -12px rgba(2, 6, 23, 0.6)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
